version: 2.1

orbs:
  ruby-orbs: sue445/ruby-orbs@volatile
  slack:     circleci/slack@3
  heroku:    circleci/heroku@volatile

executors:
  default:
    docker:
      - image: cimg/ruby:3.1.2
        environment:
          RACK_ENV: test
    working_directory: ~/app

jobs:
  rspec:
    executor:
      name: default

    steps:
      - checkout
      - ruby-orbs/bundle-install:
          cache_key_prefix: "v1-bundle"
      - run: bundle exec rspec
      - slack/notify-on-failure

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - rspec
      - heroku/deploy-via-git:
          context: Heroku
          requires:
            - rspec
          filters:
            branches:
              only: master
          post-deploy:
            - slack/status
